name: Check Webpage Changes

on:
  schedule:
    # Run every day at 7:00 AM UTC (adjust timezone as needed)
    - cron: '0 7 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need to fetch all history to track changes
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run change detection
        env:
          TRACKED_URLS: ${{ secrets.TRACKED_URLS }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python check_changes.py

      - name: Commit and push snapshot updates
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add snapshots/

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No snapshot changes to commit"
          else
            git commit -m "Update webpage snapshots - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
